version: 3.0.2.{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      APPVEYOR_JOB_NAME: "py37-x64-osx10.14"
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      APPVEYOR_JOB_NAME: "py37-x64-osx10.15"

install:
  - /usr/local/bin/python3.7 --version
  - /usr/local/bin/python3.7 -m pip install --upgrade pip
  - /usr/local/bin/python3.7 -m pip install -r requirements.txt
  - /usr/local/bin/python3.7 -m pip install codecov
  - /usr/local/bin/python3.7 -m pip install twine wheel

build_script:
  - /usr/local/bin/python3.7 setup.py bdist_wheel

test_script:
  - coverage run tests.py

artifacts:
  - path: 'dist\*.whl'
    name: pypiartifacts

after_test:
  - codecov
