version: version='3.0.4'.{build}
environment:
  TWINE_USERNAME:
    secure: kuL7IEgQ60jLJ5TXKY1C9A==
  TWINE_PASSWORD:
    secure: 7TPnKbfi538yO/KwAj5wfg==
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
    - PYTHON: "C:\\Python36"

install:
  # Prepend Python to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python3 --version
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install codecov
  - python3 -m pip install twine wheel

build_script:
  - python3 setup.py bdist_wheel

test_script:
  - coverage run tests.py

artifacts:
  - path: 'dist\*.whl'
    name: pypiartifacts

on_success:
  - codecov
  - ps: >-
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
        twine upload --skip-existing dist/*.whl
      } else {
        Write-Output "Not deploying as this is not a tagged commit"
      }
