version: 3.0.2.{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      APPVEYOR_JOB_NAME: "py37-x64-osx10.15"
      PYPATH: /usr/local/bin/python3.7

install:
  - "$env:PYPATH --version"
  - "$env:PYPATH -m pip install --upgrade pip"
  - "$env:PYPATH -m pip install -r requirements.txt"
  - "$env:PYPATH -m pip install codecov"
  - "$env:PYPATH -m pip install twine wheel"

build_script:
  - "$env:PYPATH setup.py bdist_wheel"

test_script:
  - "coverage run tests.py"

artifacts:
  - path: 'dist\*.whl'
    name: pypiartifacts

after_test:
  - "codecov"
