version: 3.0.2.{build}
environment:
  TWINE_USERNAME:
    secure: kuL7IEgQ60jLJ5TXKY1C9A==
  TWINE_PASSWORD:
    secure: 7TPnKbfi538yO/KwAj5wfg==
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      APPVEYOR_JOB_NAME: "py37-x64-osx10.15"
      PYTHON: "/usr/local/bin/python3.7"

install:
  - $PYTHON --version
  - $PYTHON -m pip install --upgrade pip
  - $PYTHON -m pip install -r requirements.txt
  - $PYTHON -m pip install codecov
  - $PYTHON -m pip install twine wheel

build_script:
  - $PYTHON setup.py bdist_wheel

test_script:
  - coverage run tests.py

artifacts:
  - path: 'dist\*.whl'
    name: pypiartifacts

after_test:
   - codecov

deploy_script:
   - twine upload --skip-existing dist\*.whl
