environment:
  matrix:
    # Ubuntu - python 3.8
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.8"
    # Ubuntu - python 3.7
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.7"
    # Ubuntu - python 3.6
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.6"
    # macos-mojave - python 3.8
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      PYTHON: "3.8"
    # macos-mojave - python 3.7
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      PYTHON: "3.7"
    # macos-mojave - python 3.6
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      PYTHON: "3.6"
    # macos-catalina - python 3.8
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      PYTHON: "3.8"
    # macos-catalina - python 3.7
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      PYTHON: "3.7"
    # macos-catalina - python 3.6
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      PYTHON: "3.6"

stack: python3 %PYTHON%

install:
  - python3 --version

build: off

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.