version: version='3.0.4'.{build}
environment:
  TWINE_USERNAME:
    secure: kuL7IEgQ60jLJ5TXKY1C9A==
  TWINE_PASSWORD:
    secure: 7TPnKbfi538yO/KwAj5wfg==
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      APPVEYOR_JOB_NAME: "py37-x64-osx10.15"
      PYTHON: "/usr/local/bin/python3.7"

    - APPVEYOR_JOB_NAME: "py36-32-win"
      PYTHON: "C:\\Python36"


install:
  - ps: "$env:PYTHON --version"
  - ps: $PYTHON -m pip install --upgrade pip
  - ps: $PYTHON -m pip install -r requirements.txt
  - ps: $PYTHON -m pip install codecov
  - ps: $PYTHON -m pip install twine wheel

build_script:
  - $PYTHON setup.py bdist_wheel

test_script:
  - coverage run tests.py

artifacts:
  - path: 'dist\*.whl'
    name: pypiartifacts

on_success:
  - ps: >-
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
        twine upload --skip-existing dist/*.whl
      } else {
        Write-Output "Not deploying as this is not a tagged commit"
      }
  - ps: >-
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
        twine upload --skip-existing dist/*.whl
      } else {
        Write-Output "Not deploying as this is not a tagged commit"
      }
