version: 3.0.2.{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      APPVEYOR_JOB_NAME: "py37-x64-osx10.14"
      PYTHON: /usr/local/bin/python3.7
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      APPVEYOR_JOB_NAME: "py37-x64-osx10.15"
      PYTHON: /usr/local/bin/python3.7

install:
  - %PYTHON% -m pip install -r requirements.txt
  - %PYTHON% -m pip install codecov

build_script:
  - %PYTHON% setup.py bdist_wheel

test_script:
  - coverage run tests.py

artifacts:
  - path: 'dist\*.whl'
    name: pypiartifacts

after_test:
  - codecov
  - %PYTHON% -m pip twine wheel
