matrix:
  include:
    - os: linux
      arch: arm64
      language: python
      python: '3.6'
      env: PYTHON=/home/travis/virtualenv/python3.6.9/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

    - os: linux
      arch: arm64
      language: python
      python: '3.7'
      env: PYTHON=/home/travis/virtualenv/python3.7.5/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

    - os: linux
      arch: arm64
      language: python
      python: '3.8'
      env: PYTHON=/home/travis/virtualenv/python3.8.0/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

install:
  - ls /home/travis/virtualenv/
  - sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade setuptools wheel twine codecov
  - python3 -m pip install -r requirements.txt
  - python3 setup.py bdist_wheel
  - ls dist/

script:
  - python3 -m coverage run tests.py

after_success:
  - python3 -m codecov

deploy:
    provider: pypi
    distributions: bdist_wheel
    file_glob: true
    file:
      - dist/*.whl
    user: aouinizied
    skip_cleanup: true
    skip_existing: true
    password:
      secure: W+ApjHVG6W1RgXwbXgC+Ucg/+ReoZDvUubQk4238iu78phjJuIpum/EMXa0pw6/eVMzuT1RSr8rGLZS81NyqLySiDQ13zXso+cjEcAq33DthAbOgIb3/q5M1HNHSzMZgF3E509QWumMtmcR4dO6ddxRYWWEk2ElLEUcYiLi2THmSDJi2w0V3Mh7CAHv24XCuyWKAXyVKbJ3ZxM5tq7HetkOT+8IAc9KxNQOp8sbIWRulpgz4LXwiLFqQBQqQ7caoubDaqzLdzIK7Yp6qtnnTBQRrVNAjNO1JDGMZduIqxnye3DyLJ/j4qQuafMaRRFyd+wZHTw3BD/AUfZ2s/aT2Yajp5mq1JJU1qd35qq+OdkiDLYYTtSPrgbr2K9639lGwP75/apGmyInasBuExdktzFHU74uE4s8aMK2xmlCNP71kJpQtp7dsPH0TdkA1eEyJWvx45K9QS2+acNnQMOIv/vtPjina7thBfTyetFVtY7/A3/Bt9PhP79qijVtgZMW4zI+8mBJSE8Gsw9QJ2RR6ztvgDqBuIanNrZA4B8Vii+6tUUm6FY0Ak3A+olxs/75hQygdbNiSsvijEsa4pSNvsJZnvh8aQhkpCm7l2Xn2eXrdJj9o6a+OjdBuracFU279mV3xqsdf22PBjnx/+klPpJFnlOlsxwZ8T5Ok7IdDtqU=
    on:
      tags: true