matrix:
  include:
    - os: linux
      arch: arm64
      language: python
      python: '3.6'
      env: PYTHON=/home/travis/virtualenv/python3.6.9/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

    - os: linux
      arch: arm64
      language: python
      python: '3.7'
      env: PYTHON=/home/travis/virtualenv/python3.7.5/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

    - os: linux
      arch: arm64
      language: python
      python: '3.8'
      env: PYTHON=/home/travis/virtualenv/python3.8.0/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

# install it
install:
  - sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels
  - pip3 install --upgrade pip
  - pip3 install --upgrade setuptools wheel twine codecov
  - pip3 install -v -r requirements.txt
  - python3 setup.py bdist_wheel
  - ls dist/

script:
  - coverage run tests.py