matrix:
  include:
    - os: linux
      arch: arm64
      language: python
      cache: pip
      python: '3.6'
      env: PYTHON=/home/travis/virtualenv/python3.6.7/bin
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

    - os: linux
      arch: arm64
      language: python
      cache: pip
      python: '3.7'
      env: PYTHON=/home/travis/virtualenv/python3.7.1/bin
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

    - os: linux
      arch: arm64
      language: python
      cache: pip
      python: '3.8'
      env: PYTHON=/home/travis/virtualenv/python3.8.0/bin
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libpcap-dev
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison


install:
  - sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels
  - pip3 install --upgrade pip
  - pip3 install --upgrade setuptools wheel twine codecov
  - travis_wait pip3 install -r requirements.txt
  - python3 setup.py bdist_wheel
  - ls dist/

script:
  - coverage run tests.py