language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - libpcap-dev
      - git
      - autogen

install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install

script:
  - coverage run tests.py

after_success:
  - codecov