language: python

python:
  - "3.6"
  - "pypy3"

addons:
  apt:
    packages:
      - libpcap-dev
      - git
      - autogen

install:
  - pip install -r requirements.txt
  - python setup.py install

script: python tests.py