version: 5.1.{build}

clone_depth: 5

matrix:
  fast_finish: true

install:
  - cd ..
  - git clone --branch libpcap-1.9.1 https://github.com/the-tcpdump-group/libpcap.git
  - cd libpcap
  - cinst winflexbison
  - win_flex --version
  - win_bison --version
  - appveyor DownloadFile https://nmap.org/npcap/dist/npcap-sdk-1.05.zip
  - 7z x .\npcap-sdk-1.05.zip -oc:\projects\libpcap\Win32\npcap-sdk-1.05
  - appveyor DownloadFile https://support.riverbed.com/bin/support/download?sid=l3vk3eu649usgu3rj60uncjqqu -FileName AirPcap_Devpack.zip
  - 7z x .\AirPcap_Devpack.zip -oc:\projects\libpcap\Win32

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "MinGW Makefiles"
      SDK: npcap-sdk-1.05
      MINGW_ROOT: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0

build_script:
  - ls
  - type NUL >.devel
  - md build
  - cd build
  - set PATH=%PATH:C:\MinGW\bin;=%
  - set PATH=%MINGW_ROOT%\mingw64\bin;%PATH%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmake -DDISABLE_AIRPCAP=YES -DPacket_ROOT=c:\projects\libpcap\Win32\%SDK% -G"%GENERATOR%" -DPacket_ROOT=c:\projects\libpcap\Win32\%SDK% -DPacket_ROOT=c:\projects\libpcap\Win32\%SDK% -G"%GENERATOR%" -DAirPcap_ROOT=c:\projects\libpcap\Win32\Airpcap_Devpack -G"%GENERATOR%" ..
  - mingw32-make
  - ls