# Documentation: https://docs.codecov.io/docs/codecov-yaml

codecov:
  # Avoid "Missing base report" due to committing CHANGES.rst with "[CI skip]"
  # https://github.com/codecov/support/issues/363
  # https://docs.codecov.io/docs/comparing-commits
  allow_coverage_offsets: true

  token: f0ecc783-444c-4970-8578-61343015e78c

comment: off
