name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
        python-version: [pypy3, 3.8, 3.7, 3.6]
        exclude:
          - os: macos-latest
            python-version: pypy3

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ubuntu Prerequisites
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install autoconf automake libtool pkg-config libpcap-dev
    - name: Installing macOS prerequisites
      if: startsWith(matrix.os, 'macOS')
      run: |
        brew install autoconf automake libtool pkg-config 
    - name: Installing package dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine setuptools codecov
        pip install -r requirements.txt
        python setup.py bdist_wheel
        ls dist/
    - name: Testing
      run: |
        coverage run tests.py

    - name: Upload coverage
      if: success()
      run: |
        codecov
